"use client";

import { usePathname } from "next/navigation";

export default function CTABanner() {
  const pathname = usePathname();

  // We can't know category from the layout alone, so homeowner articles
  // use a URL-pattern heuristic. Homeowner slugs generated by the cron
  // contain keywords like "garage", "tote", "organize", "declutter",
  // "cost", "hiring", "homeowner". Installer slugs contain "installer",
  // "contractor", "shelving-business", "profit", "margin".
  // Default to a neutral/homeowner-friendly banner on non-article pages.
  const isInstallerPage =
    /\/(installer|contractor|shelving-business|profit|margin|build-custom)/.test(
      pathname
    );

  if (isInstallerPage) {
    return (
      <div className="fixed bottom-0 left-0 right-0 z-50 border-t border-slate-700 bg-black/95 backdrop-blur-sm">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3 sm:px-6">
          <p className="text-sm font-medium text-slate-300 sm:text-base">
            Stop doing lumber math in your head. Auto-generate cut-lists and 3D
            models with{" "}
            <span className="font-bold text-white">Storage Network</span>.
          </p>
          <a
            href="https://www.storage-network.app/join"
            target="_blank"
            rel="noopener noreferrer"
            className="shrink-0 rounded-md bg-safety-orange px-5 py-2.5 text-sm font-bold uppercase tracking-wide text-black shadow-lg shadow-safety-orange/25 transition-all hover:bg-safety-yellow hover:shadow-safety-yellow/30"
          >
            Join Free
          </a>
        </div>
      </div>
    );
  }

  return (
    <div className="fixed bottom-0 left-0 right-0 z-50 border-t border-slate-700 bg-black/95 backdrop-blur-sm">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3 sm:px-6">
        <p className="text-sm font-medium text-slate-300 sm:text-base">
          Thinking about custom garage storage? Get a free quote from a
          qualified installer near you.
        </p>
        <a
          href="https://www.storage-network.app"
          target="_blank"
          rel="noopener noreferrer"
          className="shrink-0 rounded-md bg-safety-orange px-5 py-2.5 text-sm font-bold uppercase tracking-wide text-black shadow-lg shadow-safety-orange/25 transition-all hover:bg-safety-yellow hover:shadow-safety-yellow/30"
        >
          Get a Quote
        </a>
      </div>
    </div>
  );
}
